CREATE OR REPLACE FUNCTION VER_GUIAS_PAGAS_NOVO(ID_CONTR NUMBER) RETURN NUMBER IS
/*TUPAC 10/06/2019 SIS-445 CHECK THE DELCARCAO MESS*/
CT_ID NUMBER;
DIFF NUMBER;
DATA_FIM DATE;

BEGIN

DIFF := -1;

DATA_FIM :=  CASE WHEN TO_CHAR(TRUNC(SYSDATE,'DD'), 'DD') < 11 
		                   THEN TRUNC(ADD_MONTHS(SYSDATE,-2),'MM') 
		              ELSE TRUNC(ADD_MONTHS(SYSDATE,-1),'MM') END;

DBMS_OUTPUT.PUT_LINE('VERIFICACAO DE GUIAS');
SELECT ROUND(MONTHS_BETWEEN(TRUNC(DATA_INICI_ACTIV,'MM'), TRUNC(DATA_FIM,'MM')),0) INTO DIFF 
         FROM IGSS.ID_CONTR WHERE ID = ID_CONTR;

SELECT DISTINCT G.ID_CONTRIBUINTE INTO CT_ID
 FROM IGSS.ARR_GUIA G
 WHERE (G.DT_PAGAMENTO IS NOT NULL
 AND  TRUNC(G.REFERENCIA) < DATA_FIM)
 AND G.ID_CONTRIBUINTE = ID_CONTR;

DBMS_OUTPUT.PUT_LINE('CONTR_ID: '|| CT_ID);

RETURN CT_ID;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
         
    DBMS_OUTPUT.PUT_LINE('NO_DATA_FOUND, DIFF: '|| DIFF);
    IF DIFF BETWEEN 0 AND 1 THEN
         RETURN ID_CONTR;
    ELSE
        RETURN 0;
    END IF;
    
END; 
