CREATE OR REPLACE FUNCTION IGSS.VER_NUM_MESES_E_DECL_NOVO(ID_CONTR IN NUMBER) RETURN VARCHAR IS
/*Tupac 10/06/2019 SIS-445 Check the delcarcao mess*/
DATA_INI DATE;
DATA_FIM DATE;
NUM_MESES NUMBER;

BEGIN

     NUM_MESES := 1;

     SELECT TO_DATE('01/' || TO_CHAR(
            (CASE WHEN NVL(DATA_INICI_ACTIV, DATA_INSCR) < DATA_AMBIT
                       THEN DATA_AMBIT
                  ELSE NVL(DATA_INICI_ACTIV, DATA_INSCR)
              END), 'MM/YYYY'), 'DD/MM/YYYY') INTO DATA_INI FROM igss.ID_CONTR where ID = ID_CONTR;

     DATA_FIM := CASE WHEN TO_CHAR(SYSDATE, 'DD') < 11 
		                       THEN TRUNC(ADD_MONTHS(SYSDATE,-2), 'MM') 
		                  ELSE TRUNC(ADD_MONTHS(SYSDATE,-1), 'MM') END;

     DBMS_OUTPUT.PUT_LINE('DATA_INI:'|| DATA_INI || ' DATA_FIM:'|| DATA_FIM ||' MESS: '|| ROUND(MONTHS_BETWEEN(DATA_FIM, DATA_INI)));

     SELECT COUNT(*) INTO NUM_MESES FROM (
       SELECT ID_CONTR, MONTHS.REFERENCIA,
             (CASE WHEN NOT FR.DATA_REFER IS NULL THEN  'S'
               WHEN VER_CONTR_ATIVO_NA_REF(ID_CONTR, MONTHS.REFERENCIA) = 'N' THEN
                CASE
                  WHEN (select count(*) from igss.id_situa_contr isc where isc.contr_id = ID_CONTR and isc.data_inici < MONTHS.REFERENCIA) > 0 THEN 'I' ELSE 'N' END ELSE 'N' END) AS DATA_SOP,
             (CASE WHEN NOT DR.DATA_REFERENCIA IS NULL THEN 'S'
               WHEN VER_CONTR_ATIVO_NA_REF((ID_CONTR), MONTHS.REFERENCIA) = 'N' THEN
                CASE  WHEN (select count(*) from igss.id_situa_contr isc where isc.contr_id = ID_CONTR and isc.data_inici < MONTHS.REFERENCIA) > 0 THEN 'I' ELSE 'N' END ELSE 'N' END) AS DATA_SSISMO
        FROM (SELECT ADD_MONTHS(DATA_INI, ROWNUM - 1) REFERENCIA
                FROM DUAL
               WHERE MONTHS_BETWEEN(DATA_FIM, DATA_INI) >= 0
              CONNECT BY LEVEL <= ROUND(MONTHS_BETWEEN(DATA_FIM, DATA_INI))+1) MONTHS
        LEFT JOIN (SELECT DATA_REFER, CONTR_ID, COUNT(*) FROM igss.RE_FOLHA_REMUN WHERE ESTADO IN ('VA', 'CE')
                    GROUP BY DATA_REFER, CONTR_ID) FR
          ON FR.CONTR_ID = ID_CONTR
         AND FR.DATA_REFER = MONTHS.REFERENCIA
        LEFT JOIN (SELECT DATA_REFERENCIA, ID_CONTRIBUINTE, COUNT(*) FROM igss.ARR_DECLARACAO_REMUNERACAO WHERE IND_TEMP = 'N'
                    GROUP BY DATA_REFERENCIA, ID_CONTRIBUINTE) DR
          ON DR.ID_CONTRIBUINTE = ID_CONTR
         AND DR.DATA_REFERENCIA = MONTHS.REFERENCIA
    ) D WHERE (CASE WHEN D.DATA_SOP = 'S' OR D.DATA_SSISMO = 'S' THEN 'S' ELSE 'N'END) = 'N';

  IF NUM_MESES = 0
    THEN
      RETURN 'S';
   END IF;

   RETURN 'N';
END;
/
